throughput_requirement: 15
ensemble:
  response_time_range:
    max: 0.02
    min: 0.005
    avg: 0.01
    base_scale: 20
    spike_scale: 2
    noise_scale: 10
  response_time_sim: 1
  service_type: ensemble
  service_name: ensemble
  host:
    cpu: 1
inference:
  ResNet50V2:
    explainability: 0
    response_time_range:
      max: 0.5
      min: 0.1
      avg: 0.3
      base_scale: 40
      spike_scale: 3
      noise_scale: 20
    response_time_sim: 1
    service_name: ResNet50V2
    host: 
      tpu: 1
    mlmodel_name: ResNet50V2
  InceptionResNetV2:
    explainability: 1
    response_time_range:
      max: 0.5
      min: 0.1
      avg: 0.3
      base_scale: 40
      spike_scale: 3
      noise_scale: 20
    response_time_sim: 1
    service_name: InceptionResNetV2
    host: 
      cuda: 1
    mlmodel_name: InceptionResNetV2
  MobileNetV2:
    explainability: 0
    response_time_range:
      max: 0.5
      min: 0.1
      avg: 0.3
      base_scale: 40
      spike_scale: 3
      noise_scale: 20
    response_time_sim: 1
    service_name: MobileNetV2
    host: 
      cuda: 1
    mlmodel_name: MobileNetV2
processing:
  response_time_range:
    max: 0.01
    min: 0.0012
    avg: 0.003
    base_scale: 30
    spike_scale: 2
    noise_scale: 20
  response_time_sim: 1
  service_name: processing
  host: 
    cpu: 1
distribution:
  n01440764: 1
  n01443537: 1
  n01484850: 1
  n01491361: 1
  n01494475: 1
  n01496331: 0
  n01498041: 0
  n01514668: 0
  n01514859: 0
  n01518878: 0
  n01530575: 0
  n01531178: 0
  n01532829: 0
  n01534433: 0
  n01537544: 0
  n01558993: 0
  n01560419: 0
  n01580077: 0
  n01582220: 0
  n01592084: 0